### ISSUE TITLE
Translate to Rust and Bevy

### ISSUE THREAD

**Issue by naomijub** [egges/csharpgames#2]
Recently I have been trying to create content to help people (specially my son) learn Rust with Game Programming and your books has always been a reference in that subject to me. Can I translate to to Rust and Bevy instead of C# and Monogame/XNA, as well as Portuguese, and make it open source?

**Comment by egges** [comment]
Of course - feel free to translate the code to Rust. We would appreciate a link to this original repository from your repository, so that if people want to try the C# version, they can easily find it.

**Comment by naomijub** [comment]
For sure! Thank you
